### PR TITLE
Add react-router #29

### LINKED ISSUE #29: Add react-router
## Description

- add react-router
- add game view

### PR DESCRIPTION
**Pull request by syuhei176**
## Description

- use react-router and add game view.
- add link text

I wanna move button to the right side or something good position.

Closes #29

### CODE REVIEW

**Comment by ys1111** [comment]
another problem happened
excute deposit() is ok but 'amount' and 'utxos' is not refreshed

**Comment by syuhei176** [comment]
> another problem happened
> excute deposit() is ok but 'amount' and 'utxos' is not refreshed

thanks! I'll check

**Comment by syuhei176** [comment]
> another problem happened
> excute deposit() is ok but 'amount' and 'utxos' is not refreshed

@ys1111 It could not be reproduced. can you elaborate?

**Comment by ys1111** [comment]
deposit() got working! 
maybe, I have cache
I tryed, `rm -rf plasma-chamber/.db`, `indexedDB.deleteDatebase('proof')` and `localStorage.clrear()` on developer console

**Pull request merged**
